name: Call Refresh API

on:
  schedule:
    - cron: "*/10 * * * *"   # Runs every 10 minutes
  workflow_dispatch:         # Allows manual run

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API using curl
        run: |
          curl -G "https://z263442-gm167q.ps04.zwhhosting.com/n4vip/send.php" \
          --data-urlencode "pass=19b3e1848d065f2b" \
          --data-urlencode "type=refresh" \
          --data-urlencode "title=gcp" \
          --data-urlencode "message=စမ်းသေးတာပါ။"
